---
- hosts: all
  become: true
  tasks:
    - name: Install prerequisite software for Docker and docker-compose
      apt: name={{item}} state=installed
      with_items:
        - apt-transport-https
        - ca-certificates 
        - curl 
        - software-properties-common
        - python-pip

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add Dockers repository 
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable 
        state: present
        update_cache: yes

    - name: Install Docker CE
      apt: name=docker-ce state=installed

    - name: Install docker-compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.15.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

    - name: Executable permissions docker-compose
      shell: chmod +x /usr/local/bin/docker-compose