version: '2'
services:
  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    links:
      - "app"
  app:
    build:
      context: ./app
  db: 
    image: redis:alpine
    ports: 
      - "6379:6379"