version: '2'
services:
  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    links:
      - "app"
  app:
    build:
      context: ./app
    links:
      - "db"
  db: 
    image: redis:alpine